[package]
name = "foo"
version = "0.1.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2018"

[dependencies]
# chrono = "0.4"
# serde = { version = "1", features = ["derive"] }
# serde_json = "*"
# serde-value = "*"
# rand = "0.7"
# rayon = "*"
